package mapping

type FightProp string

const (

	// Base Stats
	FIGHT_PROP_BASE_ATTACK FightProp = "FIGHT_PROP_BASE_ATTACK"
	FIGHT_PROP_HP          FightProp = "FIGHT_PROP_HP"
	FIGHT_PROP_ATTACK      FightProp = "FIGHT_PROP_ATTACK"
	FIGHT_PROP_DEFENSE     FightProp = "FIGHT_PROP_DEFENSE"

	// Percent Stats
	FIGHT_PROP_HP_PERCENT      FightProp = "FIGHT_PROP_HP_PERCENT"
	FIGHT_PROP_ATTACK_PERCENT  FightProp = "FIGHT_PROP_ATTACK_PERCENT"
	FIGHT_PROP_DEFENSE_PERCENT FightProp = "FIGHT_PROP_DEFENSE_PERCENT"

	// CRIT stats
	FIGHT_PROP_CRITICAL      FightProp = "FIGHT_PROP_CRITICAL"
	FIGHT_PROP_CRITICAL_HURT FightProp = "FIGHT_PROP_CRITICAL_HURT"

	// Other Stats
	FIGHT_PROP_CHARGE_EFFICIENCY FightProp = "FIGHT_PROP_CHARGE_EFFICIENCY"
	FIGHT_PROP_HEAL_ADD          FightProp = "FIGHT_PROP_HEAL_ADD"
	FIGHT_PROP_ELEMENT_MASTERY   FightProp = "FIGHT_PROP_ELEMENT_MASTERY"

	// Damage Bonus Stats
	FIGHT_PROP_PHYSICAL_ADD_HURT FightProp = "FIGHT_PROP_PHYSICAL_ADD_HURT"
	FIGHT_PROP_FIRE_ADD_HURT     FightProp = "FIGHT_PROP_FIRE_ADD_HURT"
	FIGHT_PROP_ELEC_ADD_HURT     FightProp = "FIGHT_PROP_ELEC_ADD_HURT"
	FIGHT_PROP_WATER_ADD_HURT    FightProp = "FIGHT_PROP_WATER_ADD_HURT"
	FIGHT_PROP_WIND_ADD_HURT     FightProp = "FIGHT_PROP_WIND_ADD_HURT"
	FIGHT_PROP_ICE_ADD_HURT      FightProp = "FIGHT_PROP_ICE_ADD_HURT"
	FIGHT_PROP_ROCK_ADD_HURT     FightProp = "FIGHT_PROP_ROCK_ADD_HURT"
	FIGHT_PROP_GRASS_ADD_HURT    FightProp = "FIGHT_PROP_GRASS_ADD_HURT"
)

func (fp FightProp) String() string {
	return string(fp)
}

var FightPropMap = map[FightProp]string{
	FIGHT_PROP_BASE_ATTACK:       "Base ATK",
	FIGHT_PROP_HP:                "Flat HP",
	FIGHT_PROP_ATTACK:            "Flat ATK",
	FIGHT_PROP_DEFENSE:           "Flat DEF",
	FIGHT_PROP_HP_PERCENT:        "HP%",
	FIGHT_PROP_ATTACK_PERCENT:    "ATK%",
	FIGHT_PROP_DEFENSE_PERCENT:   "DEF%",
	FIGHT_PROP_CRITICAL:          "Crit RATE",
	FIGHT_PROP_CRITICAL_HURT:     "Crit DMG",
	FIGHT_PROP_CHARGE_EFFICIENCY: "Energy Recharge",
	FIGHT_PROP_HEAL_ADD:          "Healing Bonus",
	FIGHT_PROP_ELEMENT_MASTERY:   "Elemental Mastery",
	FIGHT_PROP_PHYSICAL_ADD_HURT: "Physical DMG Bonus",
	FIGHT_PROP_FIRE_ADD_HURT:     "Pyro DMG Bonus",
	FIGHT_PROP_ELEC_ADD_HURT:     "Electro DMG Bonus",
	FIGHT_PROP_WATER_ADD_HURT:    "Hydro DMG Bonus",
	FIGHT_PROP_WIND_ADD_HURT:     "Anemo DMG Bonus",
	FIGHT_PROP_ICE_ADD_HURT:      "Cryo DMG Bonus",
	FIGHT_PROP_ROCK_ADD_HURT:     "Geo DMG Bonus",
	FIGHT_PROP_GRASS_ADD_HURT:    "Dendro DMG Bonus",
}
